# This conda env file is for the main python environment.

---
name: hello_3D_world_env
dependencies:
  - conda-forge::alphashape=1.3.1
  - conda-forge::boto3=1.24.89
  - conda-forge::multimethod
  - conda-forge::networkx=2.8.8
  - conda-forge::numpy
  - conda-forge::pypardiso=0.4.2
  - pytorch::cpuonly=2.0
  - pytorch::pytorch=2.1.2
  - conda-forge::rtree=1.0.1
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - conda-forge::shapely=1.8.1
  - conda-forge::trimesh
  - pip
  - pip:
      - easydict==1.10
      - libigl==2.5.0
      - open3d==0.18.0
      - pymeshlab==2022.2.post2
      - triangle==20230923
      - pyyaml==6.0.1
      - psutil
      - pillow
      - xatlas==0.0.8
      - splipy==1.7.4
      - multimethod==1.9.1
      - pytest==8.0.1
      - pytest-xdist==3.5.0
      - manifold3d==2.4.5