name: Hello World Python CI

on:
  workflow_dispatch

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: hello_3D_world_env
        environment-file: conda_env.yml
        python-version: 3.10
        channels: conda-forge, pytorch
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true
        use-only-tar-bz2: true
    - run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show

    - name: Cache conda environment
      id: cache-conda-env
      uses: actions/cache@v4.0.2
      with:
        path: ~/anaconda/envs/hello_3D_world_env
        key: ${{ runner.os }}-conda-${{ hashFiles('conda_env_windows_local.yml') }}
        restore-keys: ${{ runner.os }}-conda-

    - name: Create hello_3D_world_env environment if cache is not found
      if: steps.cache-conda-env.outputs.cache-hit != 'true'
      run: |
        eval "$($HOME/anaconda/bin/conda shell.bash hook)"
        conda env create -f conda_env.yml

    - name: Activate hello_3D_world_env environment
      shell: bash
      run: |
        eval "$($HOME/anaconda/bin/conda shell.bash hook)"
        conda activate hello_3D_world_env
        conda info --envs
