name: Hello World Python CI

on:
  workflow_dispatch

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Anaconda
      run: |
        wget https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh -O anaconda.sh
        bash anaconda.sh -b -p $HOME/anaconda
        eval "$($HOME/anaconda/bin/conda shell.bash hook)"
        conda init

    - name: Configure conda channels
      run: |
        conda config --add channels conda-forge
        conda config --add channels pytorch

    - name: Cache conda environment
      id: cache-conda-env
      uses: actions/cache@v4.0.2
      with:
        path: ~/anaconda/envs/autodent
        key: ${{ runner.os }}-conda-${{ hashFiles('conda_env_windows_local.yml') }}
        restore-keys: ${{ runner.os }}-conda-

    - name: Create Autodent environment if cache is not found
      if: steps.cache-conda-env.outputs.cache-hit != 'true'
      run: |
        eval "$($HOME/anaconda/bin/conda shell.bash hook)"
        conda env create -f conda_env_windows_local.yml

    - name: Activate Autodent environment
      shell: bash
      run: |
        eval "$($HOME/anaconda/bin/conda shell.bash hook)"
        conda activate autodent
        conda info --envs
